spring:
  application:
    name: rest-with-springboot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true$serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    #root: WARN
    br.com.erudio: DEBUG

spring-doc:
  path-to-match: /api/**/v1/**
  swagger-ui:
    user-root-path: true
